# basic setting
step_per_update: 2
max_epoch : 200

# model setting
pretrained_i3d_weight : './MTL-AQA/model_rgb.pth'
RT_depth : 5
score_range : 100
voter_number : 10

# dataset setting
data_root : '/mnt/petrelfs/daiwenxun/AS-AQA/Video_result'
label_path : '/mnt/petrelfs/daiwenxun/AS-AQA/Exp/AS-AQA/Anno_result/anno_dict.pkl'
train_split : '/mnt/petrelfs/daiwenxun/AS-AQA/Exp/AS-AQA/Anno_result/train_split3.pkl'
test_split : '/mnt/petrelfs/daiwenxun/AS-AQA/Exp/AS-AQA/Anno_result/test_split3.pkl'
feature_path : '/mnt/petrelfs/daiwenxun/AS-AQA/Exp/AS-AQA/video_feature_dict.pkl'
#feature_path : '/mnt/petrelfs/daiwenxun/AS-AQA/Exp/Video-Swin-Transformer-master/video_swin_dict.pkl'
dive_number_choosing : False
usingDD: False
frame_length : 5406
seed : 0
temporal_shift_min : -3
temporal_shift_max : 3

# optimizer setting
optimizer: 'Adam'
weight_decay : 0
lr_factor : 0.01

# others
print_freq : 40

